#' At-risk-of-poverty rate
#'
#' Estimate the proportion of #' persons with equivalized disposable income
#' below the at-risk-of-poverty threshold.
#'
#' @param formula a formula specifying the income variable
#' @param design  a design object generated by the function svydesign of the library survey
#' @param order  income quantile order, usually .5
#' @param percent fraction of the quantile, usually .60
#' @param h
#' @param ARPR list generated by the function svyarpt
#' @param ncom
#' @param comp
svyarpr_lin <- function(formula, design, order = .50, percent =.6, h, ARPT, ncom, ...){
  inc <- terms.formula(formula)[[2]]
  df <- model.frame(design)
  incvar<-df[[as.character(inc)]]
  w <- weights(design)
  ARPT_val <- ARPT$value
  lin_ARPT <- ARPT$lin
  poor <- (incvar < ARPT_val) *1
  design <- update (design, poor = poor)
  ARPRC <- svymean (~poor, design = design)
  ARPRC <- coef (ARPRC)
  lin_ARPR <- icdf(formula = formula, design = design, ARPT_val, ncom=ncom, comp=TRUE)$lin +
    densfun(formula = formula, design = design , ARPT_val, htot=h, fun="F")*lin_ARPT
  list(value = ARPRC, lin = lin_ARPR)
}

svyarpr_rep <- function(formula, design, order = .50, percent =.6, ...){
  inc <- terms.formula(formula)[[2]]
  df <- model.frame(design)
  incvar<-df[[as.character(inc)]]
  w <- weights(design)
  ARPT_val <- svyarpt_rep(formula = formula, design = design, order = order,
    percent = percent,...)
  poor <- (incvar < ARPT_val) *1
  design <- update (design, poor = poor)
  ARPR <- svymean (~poor, design = design)
  ARPR <- coef (ARPRC)
  ARPR
}
