#' At-risk-of-poverty threshold
#'
#' Estimate the at-risk-of-poverty threshold.  The standard definition is to use
#' 60\% of the weighted median equivalized disposable income.
#'
#' @param formula a formula specifying the income variable
#' @param design  a design object generated by the function svydesign of the library survey
#' @param order  income quantile order, usually .5
#' @param percent fraction of the quantile, usually .60
#' @param h
#' @param ncom
#' @param comp
#' @return a list with two components: the indicator estimate \code{value} and the linearized variable \code {lin}.
#'
#' @author
#'
#' @seealso \code{\link{arpr}}
#'
#' @references Working group on Statistics on Income and Living Conditions
#' (2004) Common cross-sectional EU indicators based on EU-SILC; the gender pay
#' gap.  \emph{EU-SILC 131-rev/04}, Eurostat.
#'
#' @keywords survey
#'
#' @examples
#' library(vardpoor)
#' data(eusilc)
#' library(survey)
#' htot <- h_fun(eusilc$eqIncome, eusilc$rb050)
#' des_eusilc <- svydesign(ids=~db040, weights=~rb050, data=eusilc)
#' svyarpt(~eqIncome, design=des_eusilc, .5, .6, h = htot, ncom=nrow(eusilc), comp=TRUE)
#'
#' @export

svyarpt.survey.design <- function(formula, design, order = .50, percent =.6, h, ncom, comp,...) {
  w <- weights(design)
  ind<-names(w)
  quant_val<- svyquantile(x = formula, design=design,
    quantiles = order, method="constant")
  quant_val <- as.vector(quant_val)
  ARPT <- percent* quant_val
  lin_ARPT <- percent * iqalpha(formula = formula, design = design,
    alpha = order,h=h, ncom=ncom, comp=FALSE,incvec = NULL)$lin
  names(lin_ARPT)<-ind
  lin_ARPT_comp<-complete(lin_ARPT, ncom)
  if(comp)lin<-lin_ARPT_comp else lin<-lin_ARPT
  list(value = ARPT, lin = lin)
}

svyarpt.svyrep.design <- function(formula, design, order = .50, percent =.6,...) {
  w <- weights(design)
  ind<-names(w)
  quant_val<- svyquantile(x = formula, design=design,
    quantiles = order, method="constant")
  quant_val <- as.vector(quant_val)
  ARPT <- percent* quant_val
  ARPT
}


svyarpt <- 
	function( formula , design , ... ){
		
		UseMethod( "svyarpt" , design )
		
	}


