#' Relative median poverty gap
#'
#' Estimate the difference between the poverty threshold \code{arpt} and the median of  incomes less than the \code{arpt} relative to the \code{arpt}.
#'
#'
#' @param formula a formula specifying the income variable
#' @param design  a design object generated by the function svydesign of
#' the library survey
#' @param order  income quantile order, usually .5
#' @param percent fraction of the quantile, usually .60
#' @param h bandwidth to estimate the derivative of the cdf function computed from
#' the whole sample
#' @param ARPR list generated by the function svyarpt
#' @param ncom length of the income vector for the whole sample
#' @param comp logical variable \code{TRUE} if the inearized variable for domains
#' should be completed with zeros
#'
#' @return a list with two components: the indicator estimate \code{value}
#' and the linearized variable \code {lin}.
#'
#' @author Djalma Pessoa and Anthony Damico
#'
#' @seealso \code{\link{arpt}}
#'
#' @references Guillaume Osier (2009). Variance estimation for complex indicators
#'of poverty and inequality. \emph{Journal of the European Survey Research
#' Association}, Vol.3, No.3, pp. 167-195,
#' ISSN 1864-3361, URL \url{http://ojs.ub.uni-konstanz.de/srm/article/view/369}.

#'Jean-Claude Deville (1999). Variance estimation for complex statistics and estimators: #'linearization and residual techniques. Survey Methodology, 25, 193-203,
#' URL \url{http://www5.statcan.gc.ca/bsolc/olc-cel/olc-cel?lang=eng&catno=12-001-X19990024882}.
#'
#' @keywords survey
#'
#' @examples
#' library(vardpoor)
#' data(eusilc)
#' library(survey)
#' htot <- h_fun(eusilc$eqIncome, eusilc$rb050)
#' des_eusilc <- svydesign(ids=~db040, weights=~rb050, data=eusilc)
#' arpt_eusilc <- svyarpt(~eqIncome, design=des_eusilc, .5, .6, h = htot,
#' ncom=nrow(eusilc), comp=TRUE)
#' rmpg_eulsilc<- svyrmpg_lin(~eqIncome, design=des_eusilc, order =.50,
#' percent = .60,  h = htot, ncom=nrow(eusilc), comp=TRUE,
#' comp=TRUE, ARPT = arpt_eusilc)
#'
#' @export


svyrmpg_lin <- function(formula, design, order =.50, percent = .60, ncom , h, comp, ARPT, ...){
  w<-weights(design)
  ind<-names(w)
  N<-sum(w)
  inc <- terms.formula(formula)[[2]]
  df <- model.frame(design)
  incvar<-df[[as.character(inc)]]
  arpt <- ARPT$value
  linarpt <- ARPT$lin
  arpr <-sum((incvar<=arpt)*w)/N
  dsub<- subset (design, subset= (incvar<= arpt))
  medp <- svyquantile(x = formula, dsub, .5, method="constant")
  medp<-as.vector(medp)
  RMPG <- 1 - (medp/ arpt)
  Fprimemedp <- densfun(formula = formula, design = design , medp, htot=h, fun="F")
  Fprimearpt<-  densfun(formula = formula, design = design, arpt, htot=h, fun="F")
  # linearize cdf of ARPT
  ifarpr0<-(1/N)*((incvar<=arpt)-arpr)
  names(ifarpr0)<-names(w)
  ifarpr0<-complete(ifarpr0,ncom)
  ifarpr <- ifarpr0+Fprimearpt*linarpt
  # linearize cdf of medp
  ifmedp <-(1/N)*((incvar<=medp)-0.5*arpr)
  names(ifmedp) <- names(w)
  ifmedp<- complete(ifmedp, ncom)
  # linearize median of poor
  linmedp <- (0.5*ifarpr-ifmedp)/Fprimemedp
  # linearize RMPG
  linrmpg <- (medp*linarpt/(arpt*arpt))-(linmedp/arpt)
  list(value = RMPG, lin = linrmpg)
}

svyrmpg_rep <- function(formula, design, order =.50, percent = .60, ARPT, ...){
  w<-weights(design)
  ind<-names(w)
  N<-sum(w)
  inc <- terms.formula(formula)[[2]]
  df <- model.frame(design)
  incvar<-df[[as.character(inc)]]
  arpt <- svyarpt_rep(formula = formula, design = design, order = order,
    percent =percent,...)
  arpr <-sum((incvar<=arpt)*w)/N
  dsub<- subset (design, subset= (incvar<= arpt))
  medp <- svyquantile(x = formula, dsub, .5, method="constant")
  medp<-as.vector(medp)
  RMPG <- 1 - (medp/ arpt)
  RMPG
}
